- hosts: all
  tasks:

  - set_fact:
      ceph_dev_branch: wip-rocksdb-jewel-patches

  - name: install EPEL
    package:
      name: epel-release
      state: present

  - name: fetch ceph red hat development repository
    uri:
      url: https://shaman.ceph.com/api/repos/ceph/{{ ceph_dev_branch }}/latest/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/repo
      return_content: yes
    register: ceph_dev_yum_repo

  - debug:
      msg: "{{ ceph_dev_yum_repo }}"

  - name: configure ceph red hat development repository
    copy:
      content: "{{ ceph_dev_yum_repo.content }}"
      dest: /etc/yum.repos.d/ceph-dev.repo
      owner: root
      group: root
      backup: yes

  - package:
      name: ceph
      state: present
